const char* html_page =
"<!DOCTYPE html>\n"
"<html>\n"
"  <head>\n"
"    <title>Mobil Resing</title>\n"
"  </head>\n"
"  <body>\n"
"    <p><button id=\"maju\" style=\"user-select:none; -webkit-user-select: none; -moz-user-select: none; -webkit-touch-callout: none;\">Maju</a></p>\n"
"    <p><button id=\"mundur\" style=\"user-select:none; -webkit-user-select: none; -moz-user-select: none; -webkit-touch-callout: none;\">Mundur</a></p>\n"
"    <script>\n"
"      const maju = document.getElementById(\"maju\");\n"
"      maju.addEventListener(\"touchstart\", (e) => {fetch('/maju');e.preventDefault()}, {passive: false})\n"
"      maju.addEventListener(\"touchend\", () => fetch('/stop'))\n"
"      const mundur = document.getElementById(\"mundur\");\n"
"      mundur.addEventListener(\"touchstart\", (e) => {fetch('/mundur');e.preventDefault()}, {passive: false})\n"
"      mundur.addEventListener(\"touchend\", () => fetch('/stop'))\n"
"    </script>\n"
"  </body>\n"
"</html>\n";
